export const COMPUTER_USE_COPY = {
  metaTitle: { en: "Computer Use for Mac · Codewhale", zh: "Mac 版 Computer Use · Codewhale" },
  metaDescription: { en: "Download and set up Codewhale Computer Use for Mac. Background app control, permission setup, and human Pause and Stop controls.", zh: "下载并设置 Mac 版 Codewhale Computer Use。提供应用后台操作、权限设置，以及由用户控制的暂停和停止功能。" },
  title: { en: "Computer Use", zh: "Computer Use" },
  lead: { en: "Let Codewhale work in your apps while you keep working. The Mac helper brings permissions, background app control, and a way to pause or stop input to your menu bar.", zh: "让 Codewhale 在应用中完成操作，你也可以继续工作。Mac 助手将权限设置、应用后台操作，以及暂停或停止输入的控制集中在菜单栏中。" },
  publisher: { en: "By Codewhale", zh: "由 Codewhale 开发" },
  download: { en: "Download for Mac", zh: "下载 Mac 版" },
  requirements: { en: "macOS 13.5 or later · Apple silicon and Intel", zh: "macOS 13.5 或更高版本 · Apple 芯片与 Intel" },
  included: { en: "One app download. No separate Node installation or compiler required.", zh: "只需下载一个应用，无需另行安装 Node 或编译器。" },
  pendingTitle: { en: "Mac download in preparation", zh: "Mac 下载包准备中" },
  pendingBody: { en: "The public installer will appear here after Apple notarization and release checks are complete.", zh: "完成 Apple 公证和发布检查后，正式安装包将在此提供。" },
  unavailableTitle: { en: "Download availability could not be checked", zh: "暂时无法查询下载状态" },
  unavailableBody: { en: "Refresh this page to try again, or check the published releases below.", zh: "请刷新页面重试，或通过下方链接查看已发布版本。" },
  releases: { en: "Published releases", zh: "已发布版本" },
  receipt: { en: "Download verification details", zh: "下载校验信息" },
  setup: { en: "Set up your Mac", zh: "设置你的 Mac" },
  steps: [
    { title: { en: "Open the app", zh: "打开应用" }, body: { en: "Expand the download, move Codewhale Computer Use to Applications, and open it. Choose Computer Use from the whale icon in your menu bar.", zh: "解压下载文件，将 Codewhale Computer Use 移入“应用程序”并打开。点击菜单栏中的鲸鱼图标，选择 Computer Use。" } },
    { title: { en: "Review permissions", zh: "检查权限" }, body: { en: "Use the setup buttons to open Accessibility and Screen Recording in System Settings. You choose which permissions to grant.", zh: "通过设置按钮打开系统设置中的“辅助功能”和“屏幕录制”。由你决定授予哪些权限。" } },
    { title: { en: "Run the background check", zh: "运行后台检查" }, body: { en: "The helper opens a disposable practice window, enters text, and captures that window. It checks whether the pointer or active app changed during the run.", zh: "助手会打开一个临时练习窗口，输入文本并截取该窗口，同时检查运行期间指针或前台应用是否发生变化。" } },
    { title: { en: "Connect it to Codewhale", zh: "连接 Codewhale" }, body: { en: "Review, trust, and enable Computer Use in Codewhale’s plugin marketplace. Use plugin 0.3.0 or later so local actions go through the helper’s Pause and Stop controls.", zh: "在 Codewhale 插件市场中审查、信任并启用 Computer Use。请使用 0.3.0 或更高版本，确保本地操作受助手的暂停和停止控制。" } },
  ],
  controlsTitle: { en: "Keep working. Keep control.", zh: "继续工作，掌握控制权。" },
  controlsBody: { en: "Supported actions operate on the selected app in the background. Apps and gestures that need foreground control require your authorization. The menu shows the target and input mode; Pause suspends helper input, and Stop ends its existing sessions.", zh: "受支持的操作可在选定应用的后台完成。需要前台控制的应用或手势必须得到你的授权。菜单会显示目标应用与输入模式；Pause 暂停助手输入，Stop 结束助手的现有会话。" },
  updateTitle: { en: "Updates when you choose", zh: "由你决定何时更新" },
  updateBody: { en: "Choose Check for updates from the app. Before installing an update, it checks the download, Codewhale signature, and Apple notarization, and keeps the previous app for recovery.", zh: "在应用中选择 Check for updates。安装更新前，助手会校验下载文件、Codewhale 签名和 Apple 公证，并保留旧版应用以便恢复。" },
  help: { en: "Setup and troubleshooting", zh: "设置与故障排查" },
  notes: { en: "Release notes", zh: "版本说明" },
  demo: { en: "See the background check", zh: "查看后台检查演示" },
  source: { en: "Source and other platforms", zh: "源码与其他平台" },
  platforms: { en: "This download is for Mac. Windows and Linux currently use the source plugin and host-side setup.", zh: "此下载适用于 Mac。Windows 和 Linux 目前通过源码插件及宿主端设置使用。" },
  installTitle: { en: "Computer Use for Mac", zh: "Mac 版 Computer Use" },
  installLead: { en: "Add background app control with the Computer Use helper. Set up Mac permissions, run a background check, and pause or stop helper input from your menu bar.", zh: "通过 Computer Use 助手添加应用后台操作能力。设置 Mac 权限、运行后台检查，并从菜单栏暂停或停止助手输入。" },
  installLink: { en: "Computer Use download and setup", zh: "Computer Use 下载与设置" },
} as const;
